import "@/assets/stylesheets/globals.css";
import { Toaster } from "@/components/ui/Toaster";
import { Providers } from "@/lib/utils/providers";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="min-h-svh bg-slate-50">
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
