import { getCurrentUser } from "@/actions/auth";
import "@/assets/stylesheets/globals.css";
import Sidebar from "@/components/layouts/Sidebar";
import { Toaster } from "@/components/ui/Toaster";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="grid min-h-svh grid-cols-[auto_auto] gap-4 bg-slate-50">
        <Sidebar currentUser={currentUser} />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
